# Generated by Django 2.2.6 on 2019-11-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture1',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture2',
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
