# Generated by Django 2.2.6 on 2019-12-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
